## 投影
### PCA

In [10]:
import numpy as np
m = 60
np.random.seed(4)
w1, w2 = 0.1, 0.3
noise = 0.1
angles = np.random.rand(m) * 3 * np.pi / 2 - 0.5
X = np.empty((m, 3))
X[:, 0] = np.cos(angles) + np.sin(angles)/2 + noise * np.random.randn(m) / 2
X[:, 1] = np.sin(angles) * 0.7 + noise * np.random.randn(m) / 2
X[:, 2] = X[:, 0] * w1 + X[:, 1] * w2 + noise * np.random.randn(m)

In [11]:
# 使用主成分分析,返回一个经过主成分变换的实例数组
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X2D = pca.fit_transform(X)

In [12]:
# pca属性访问
pca.explained_variance_ratio_

array([0.84248607, 0.14631839])

In [14]:
# 打印所有主成分，每一个主成分为一个水平向量
pca.components_

array([[-0.93636116, -0.29854881, -0.18465208],
       [ 0.34027485, -0.90119108, -0.2684542 ]])

In [20]:
pca = PCA()
pca.fit(X)

cumsum = np.cumsum(pca.explained_variance_ratio_)
# 找出所有累计解释率大于0.95的所有组合，取索引
d = np.argmax(cumsum>=0.95) + 1

In [21]:
pca = PCA(n_components=0.95)
X_reduced = pca.fit_transform(X)

In [23]:
pca.components_

array([[-0.93636116, -0.29854881, -0.18465208],
       [ 0.34027485, -0.90119108, -0.2684542 ]])

## 增量PCA

In [ ]:
from sklearn.decomposition import IncrementalPCA
n_batches =100
for X_batch in np.array_split(X)

In [26]:
x=np.random.rand(19)
np.split(x, 4)

ValueError: array split does not result in an equal division

In [27]:
np.array_split(x, 4)

[array([0.4002717 , 0.5712342 , 0.11948192, 0.79618438, 0.32375196]),
 array([0.11562865, 0.70719985, 0.51490824, 0.0271004 , 0.56278361]),
 array([0.76420884, 0.03104267, 0.65758762, 0.25014191, 0.43527631]),
 array([0.07216742, 0.53222852, 0.93882891, 0.30481571])]